### ISSUE TITLE
Can't read modules import - libsass supported?

### ISSUE THREAD

**Issue by ronilaukkarinen** [designbyjake/sassline#27]
Just cloned the repo, getting this:

	[21:06:02] [gulp-sass] file to import not found or unreadable: modules/*.*
	Current dir: /Users/rolle/Projects/dudetest/content/themes/dudestarter/sass/typography/sassline/assets/sass/ on line 13 in /Users/rolle/Projects/dudetest/content/themes/dudestarter/sass/typography/sassline/assets/sass/style.scss

It works with:

	// Import all SCSS modules with Sass globbing.
	@import "modules/footer";
	@import "modules/globals";
	@import "modules/header";
	@import "modules/nav";

**Comment by ronilaukkarinen** [comment]
Oh, figured out this is a globbing thingy. Well, Gulp does not seem to have working globbing at the moment, I have already opened an issue [here](https://github.com/jsahlen/gulp-css-globbing/issues/20).

Nevertheless, isn't having to install a separate plugin for just one include a bit too overkill?

**Comment by designbyjake** [comment]
@ronilaukkarinen I prefer to work in multiple scss partials so it is much nicer if they just get auto imported by globbing as outlined in the readme. If you dont then you can just run it without globbing as you have shown.

**Comment by ronilaukkarinen** [comment]
Ok, I'll have my way around gulp globbing. Thanks for the answer!

**Comment by zacwasielewski** [comment]
I second @ronilaukkarinen's issue. Sassline won't work with gulp/libsass, since [libsass intentionally doesn't support globbing within partials](https://github.com/sass/libsass/issues/156#issuecomment-34151696). And unfortunately, there's no gulp plugin to work around the issue (I tried hacking [`gulp-css-globbing`](https://github.com/jsahlen/gulp-css-globbing), but it's not a trivial change.)

@designbyjake, I totally understand your preference for auto imported globbing – I prefer it too. But with gulp *and* libsass gaining popularity, is there any chance you'd reconsider, simply because it will open up Sassline to gulp/libsass users?

(I'm personally handling it by keeping my own, modified fork – but it sure would be nice to point to the official repo. Oh, and thanks for your work on Sassline – it's really an awesome project!)

**Comment by ronilaukkarinen** [comment]
@zacwasielewski I agree. Didn't get my way around with libsass + globbing after all and ended up using modified fork myself as well, but it would be nice to use the official bower package without modifications and to get all the updates and keep the fiels clean in the future.

**Comment by designbyjake** [comment]
Reopening, thinking on this some more.

**Comment by jacmoe** [comment]
If it helps your thinking, then I'd add that it goes against the rules set forth in the sass guidelines: 
-  I would not recommend it because it imports files following the alphabetical order which is usually not - what you want, especially when dealing with a source-order dependent language.

**Comment by strarsis** [comment]
For node_modules that aren't sass eyeglass compatible yet, 
you can use [sass-include-paths](https://www.npmjs.com/package/sass-include-paths) 
which will autogenerate the right include paths for you.

With best regards

**Comment by designbyjake** [comment]
I’m planning to removing globbing soon :+1:

**Comment by designbyjake** [comment]
Globbing removed

**Comment by ronilaukkarinen** [comment]
It seems the [npm package](https://www.npmjs.com/package/sassline) is not updated?

**Comment by jakegiltsoff** [comment]
@ronilaukkarinen Should be updated now!

**Comment by ronilaukkarinen** [comment]
Thank you @jakegiltsoff!
